
<style>
	.card-body {
		padding: 10px;
	}
	a:hover {
		text-decoration: none;
	}
</style>
<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/timeline">
	  		Home
	  	</a>

	  	<a class="menuItem" href="/sair">
	  		Sair
	  	</a>
			<img src="/img/twitter_logo.png" class="menuIco" />
	  </div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">
		
		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">

				</div>

				<div class="perfilPainel">
					
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome"><?php echo $this->view->info_usuario['nome'] ?></span>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">
							<a href="/timeline">
								<span class="perfilPainelItem">Tweets</span><br />
								<span class="perfilPainelItemValor"><?php echo $this->view->total_tweets['total_tweet'] ?></span>
							</a>
						</div>

						<div class="col">
							<a href="/timelineSeguindo">
								<span class="perfilPainelItem">Seguindo</span><br />
								<span class="perfilPainelItemValor"><?php echo $this->view->total_seguindo['total_seguindo'] ?></span>
							</a>
						</div>

						<div class="col">
							<a href="/timelineSeguidores">
								<span class="perfilPainelItem">Seguidores</span><br />
								<span class="perfilPainelItemValor"><?php echo $this->view->total_seguidores['total_seguidores'] ?></span>
							</a>
						</div>

					</div>

				</div>
			</div>

		</div>

		<div class="col-md-6">
			
			<div class="row mb-2">
				<div class="col">
					<div class="card">
						<div class="card-body">
							<form method="get" action="/quem_seguir">
								<div class="input-group mb-3">
									<input type="text" name="pesquisarPor" class="form-control" placeholder="Quem você está procurando?">
									<div class="input-group-append">
										<button class="btn btn-primary" type="submit">Procurar</button>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>

			<?php foreach($this->view->usuarios as $indice_arr => $usuario) { ?>
				<div class="row mb-2">
					<div class="col">
						<div class="card">
							<div class="card-body">
								<div class="row">
									<div class="col-md-6">
										<?php echo $usuario['nome'] ?>
									</div>
								
									<div class="col-md-6 d-flex justify-content-end">
										<div>
											<?php
											if($usuario['seguindo_sn'] == 0) { ?> 
												<a href="/acao?acao=seguir&id_usuario=<?php echo $usuario['id']?>&pag=quem_seguir" class="btn btn-info">Seguir</a>
						
											<?php } ?>

											<?php
											if($usuario['seguindo_sn'] > 0) { ?> 
												<a href="/acao?acao=deixar_de_seguir&id_usuario=<?php echo $usuario['id']?>&pag=quem_seguir" class="btn btn-secondary">Deixar de seguir</a>
						
											<?php } ?>
											
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			<?php } ?>
		</div>

		<div class="col-md-3">
			<div class="card">
				<h4 style="font-size: 15px; color: #1DA1F2; font-weight: bold;" class="card-header">Sugestões:</h4>
					<div class="card-body">
					<?php foreach($this->view->sugestoes as $indice_arr => $sugestao) { ?>
						<?php
						if($sugestao['seguindo_sn'] == 0) { ?>
							<div class="row mb-2">
							<div class="col">
								<div class="card">
									<div class="card-body">
										<div class="row">
											<div class="col-md-9">
												<?php echo $sugestao['nome'] ?>
											</div>
											<div class="col-md-3 d-flex justify-content-end">
											<div>
												<a href="/acao?acao=seguir&id_usuario=<?php echo $sugestao['id']?>&pag=quem_seguir" class="btn btn-info" style="font-size: 10px;">Seguir</a>
											</div>
										</div>
										</div>
									</div>
								</div>
							</div>
						</div>
						<?php } ?>
			
					<?php } ?>
				</div>
			</div>
		</div>
	</div>
</div>