<style>
	.card-body {
		padding: 10px;
	}
	#seguidoresPagina {
		background-color: #1DA1F2;
		color: white;
	}
	a:hover {
		text-decoration: none;
	}
</style>

<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/timeline">
	  		Home
	  	</a>

	  	<a class="menuItem" href="/sair">
	  		Sair
	  	</a>
			<img src="/img/twitter_logo.png" class="menuIco" />
	  </div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">
		
		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">

				</div>

				<div class="perfilPainel">
					
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome"><?php echo $this->view->info_usuario['nome'] ?></span>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">
							<a href="/timeline">
								<span class="perfilPainelItem">Tweets</span><br />
								<span class="perfilPainelItemValor"><?php echo $this->view->total_tweets['total_tweet'] ?></span>
							</a>
						</div>

						<div class="col">
							<a href="/timelineSeguindo">
								<span class="perfilPainelItem">Seguindo</span><br />
								<span class="perfilPainelItemValor"><?php echo $this->view->total_seguindo['total_seguindo'] ?></span>
							</a>
						</div>

						<div class="col">
							<a href="/timelineSeguidores">
								<span class="perfilPainelItem">Seguidores</span><br />
								<span class="perfilPainelItemValor"><?php echo $this->view->total_seguidores['total_seguidores'] ?></span>
							</a>
						</div>

					</div>

				</div>
			</div>

			
			<div class="card d-none d-md-block">
				<h4 style="font-size: 15px; color: #1DA1F2; font-weight: bold;" class="card-header">Seguidores:</h4>
					<div class="card-body">
						<?php foreach($this->view->seguidores as $indice_arr => $seguidor) { ?>
							<div class="row mb-2">
								<div class="col">
									<div class="card">
										<div class="card-body">
											<div class="row">
												<div class="col-md-9">
													<?php echo $seguidor['nome'] ?>
												</div>
												<div class="col-md-3 d-flex justify-content-end">
												<div>
													<?php
													if($seguidor['seguindo_sn'] == 0) { ?>
														<a href="/acao?acao=seguir&id_usuario=<?php echo $seguidor['id_usuario']?>&pag=timelineSeguidores" class="btn btn-info" style="font-size: 10px;">Seguir</a>
													<?php } ?>
													<?php
													if($seguidor['seguindo_sn'] > 0) { ?>
														<a href="/acao?acao=deixar_de_seguir&id_usuario=<?php echo $seguidor['id_usuario']?>&pag=timelineSeguidores" class="btn btn-secondary" style="font-size: 10px;">Deixar de seguir</a>
													<?php } ?>
												</div>
											</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						<?php } ?>
						
					</div>
			</div>
			

		</div>

		

		<div class="col-md-6">
			
			<div class="card">
				<h4 class="card-header" id="seguidoresPagina">Seguidores</h4>
				<div class="card-body">
				<?php foreach($this->view->seguidoresPaginar as $indice_arr => $seguidor) { ?>
							<div class="row mb-2">
								<div class="col">
									<div class="card">
										<div class="card-body">
											<div class="row">
												<div class="col-md-9">
													<?php echo $seguidor['nome'] ?>
												</div>
												<div class="col-md-3 d-flex justify-content-end">
												<div>
													<?php
													if($seguidor['seguindo_sn'] == 0) { ?>
														<a href="/acao?acao=seguir&id_usuario=<?php echo $seguidor['id_usuario']?>&pag=timelineSeguidores" class="btn btn-info" style="font-size: 10px;">Seguir</a>
													<?php } ?>
													<?php
													if($seguidor['seguindo_sn'] > 0) { ?>
														<a href="/acao?acao=deixar_de_seguir&id_usuario=<?php echo $seguidor['id_usuario']?>&pag=timelineSeguidores" class="btn btn-secondary" style="font-size: 10px;">Deixar de seguir</a>
													<?php } ?>
												</div>
											</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						<?php } ?>
				</div>
			</div>

			<div class="row mt-5 justify-content-center align-itens-center">
				<nav aria-label="...">
					<ul class="pagination">
						<li class="page-item">
						<a class="page-link" href="/timelineSeguidores?pagina=1" tabindex="-1">Primeira</a>
						</li>
						<?php 
							for($i = 1; $i <= $this->view->total_de_paginas; $i++) { ?>
								<li class="page-item <?php echo $this->view->pagina_ativa== $i ? 'active' : ''  ?>"><a class="page-link" href="/timelineSeguidores?pagina=<?php echo $i?>"><?php echo $i ?></a></li>
								<li class="page-item active">
						<?php } ?>
						
						</li>
						<li class="page-item">
							<a class="page-link" href="/timelineSeguidores?pagina=<?php echo $this->view->total_de_paginas?>">Última</a>
						</li>
					</ul>
				</nav>
			</div>

		</div>


		<div class="col-md-3">
			<div class="quemSeguir">
				<span class="quemSeguirTitulo">Quem seguir</span><br />
				<hr />
				<a href="/quem_seguir" class="quemSeguirTxt">Procurar por pessoas conhecidas</a>
			</div>
		</div>

	</div>
</div>