<!-- Font Awesome -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
<style>
	.card-body {
		padding: 10px;
	}
	a:hover {
		text-decoration: none;
	}
</style>

<script>
	function mudarBotao(param) {
		if(param == 0) {
			let edicao = document.getElementById('mostrarEdicao')
			edicao.style.display = 'block'
		}
		if(param == 1) {
			let edicao = document.getElementById('esconderEdicao')
			edicao.style.display = 'none'
		}
	}
</script>

<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/timeline">
	  		Home
	  	</a>

	  	<a class="menuItem" href="/sair">
	  		Sair
	  	</a>
			<img src="img/twitter_logo.png" class="menuIco" />
	  </div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">
		
		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">

				</div>

				<div class="perfilPainel">
					
					<div class="row mt-2 mb-2">
						<div class="col-12 mb-2">
							<span class="perfilPainelNome"><?php echo $this->view->info_usuario['nome'] ?></span>
							<button class="btn btn-outline-primary ml-2" onclick="mudarBotao(0)"><i class="far fa-edit"></i></button>
						</div>
						<div id="mostrarEdicao" class="col-12" style="display:none">
							<form action="/editar_nome" class="" method="POST">
								<div class="form-row input-group input-group-sm">
									<div class="col-8"><input id="" type="text" name="nome" class="form-control" ></div>
									<div class="col-3 ml-2"><button class="btn btn-outline-success form-control" id="esconderEdicao" onclick="mudarBotao(1)"><i class="fas fa-check"></i></button></div>
								</div>
							</form>
						</div>
						<?php if(isset($_GET['edicao']) && $_GET['edicao'] == 'erro') { ?>
							<div class="col-12">
								<span class="text-danger">Insira um nome com pelo menos 3 caracteres válidos</span>
							</div>
						<?php } ?>
						<?php if(isset($_GET['edicao']) && $_GET['edicao'] == 'sucesso') { ?>
							<div class="col-12">
								<span class="text-success">Nome alterado com sucesso</span>
							</div>
						<?php } ?>
					</div>

					<div class="row mb-2">

						<div class="col">
							<a href="/timeline">
								<span class="perfilPainelItem">Tweets</span><br />
								<span class="perfilPainelItemValor"><?php echo $this->view->total_tweets['total_tweet'] ?></span>
							</a>
						</div>

						<div class="col">
							<a href="/timelineSeguindo">
								<span class="perfilPainelItem">Seguindo</span><br />
								<span class="perfilPainelItemValor"><?php echo $this->view->total_seguindo['total_seguindo'] ?></span>
							</a>
						</div>

						<div class="col">
							<a href="/timelineSeguidores">
								<span class="perfilPainelItem">Seguidores</span><br />
								<span class="perfilPainelItemValor"><?php echo $this->view->total_seguidores['total_seguidores'] ?></span>
							</a>
						</div>

					</div>

				</div>
			</div>

			
			<div class="card d-none d-md-block">
				<h4 style="font-size: 15px; color: #1DA1F2; font-weight: bold;" class="card-header">Seguidores:</h4>
					<div class="card-body">
						<?php foreach($this->view->seguidores as $indice_arr => $seguidor) { ?>
							<div class="row mb-2">
								<div class="col">
									<div class="card">
										<div class="card-body">
											<div class="row">
												<div class="col-md-9">
													<?php echo $seguidor['nome'] ?>
												</div>
												<div class="col-md-3 d-flex justify-content-end">
												<div>
													<?php
													if($seguidor['seguindo_sn'] == 0) { ?>
														<a href="/acao?acao=seguir&id_usuario=<?php echo $seguidor['id_usuario']?>&pag=timeline" class="btn btn-info" style="font-size: 10px;">Seguir</a>
													<?php } ?>
													<?php
													if($seguidor['seguindo_sn'] > 0) { ?>
														<a href="/acao?acao=deixar_de_seguir&id_usuario=<?php echo $seguidor['id_usuario']?>&pag=timeline" class="btn btn-secondary" style="font-size: 10px;">Deixar de seguir</a>
													<?php } ?>
												</div>
											</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						<?php } ?>
						<?php if($this->view->limite_seguidores < $this->view->total_seguidores['total_seguidores']) { ?>
							<a href="/timelineSeguidores">Ver todos</a>
						<?php } ?>
					</div>
			</div>
			

		</div>

		

		<div class="col-md-6">
			<div class="row mb-2">
				<div class="col tweetBox">
					<form method="post" action="/tweet">
						<textarea class="form-control" name="tweet" id="exampleFormControlTextarea1" rows="3"></textarea>
						
						<div class="col mt-2 d-flex justify-content-end">
							<button type="submit" class="btn btn-primary">Tweet</button>
						</div>

					</form>
				</div>
			</div>

			<?php foreach($this->view->tweets as $id_tweet => $tweet) { ?>
				<div class="row tweet" id="<?php echo $tweet['id'] ?>">
					<div class="col">
						<p><strong><?=$tweet['nome']?></strong> <small><span class="text text-muted">- <?=$tweet['data']?></span></small></p>
						<p><?=$tweet['tweet']?></p>
						<br />
						<?php 
						if($tweet['id_usuario'] == $_SESSION['id']) { ?> 
							<form method="post" action="/remover_tweet?id=<?php echo $tweet['id']?>">
							<div class="col d-flex justify-content-end">
								<button type="submit" class="btn btn-outline-danger"><i class="far fa-trash-alt"></i></button>
							</div>
							</form>
						<?php } ?>
					</div>
				</div>
			<?php } ?>

			<div class="row mt-5 justify-content-center align-itens-center">
				<nav aria-label="...">
					<ul class="pagination">
						<li class="page-item">
						<a class="page-link" href="/timeline?pagina=1" tabindex="-1">Primeira</a>
						</li>
						<?php 
							for($i = 1; $i <= $this->view->total_de_paginas; $i++) { ?>
								<li class="page-item <?php echo $this->view->pagina_ativa== $i ? 'active' : ''  ?>"><a class="page-link" href="/timeline?pagina=<?php echo $i?>"><?php echo $i ?></a></li>
								<li class="page-item active">
						<?php } ?>
						
						</li>
						<li class="page-item">
							<a class="page-link" href="/timeline?pagina=<?php echo $this->view->total_de_paginas?>">Última</a>
						</li>
					</ul>
				</nav>
			</div>


		</div>


		<div class="col-md-3">
			<div class="quemSeguir">
				<span class="quemSeguirTitulo">Quem seguir</span><br />
				<hr />
				<a href="/quem_seguir" class="quemSeguirTxt">Procurar por pessoas conhecidas</a>
			</div>
		</div>

	</div>

</div>



